session_fileupload/feedback/feedback/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("reviews.urls")),
    path('users/', include("django.contrib.auth.urls")), # /login, logout. password-change
    path('users/', include("feedbackusers.urls")),
    path('profiles/', include("profiles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

session_fileupload/feedback/feedbackusers/urls.py
from django.urls import path
from .views import UserRegistrationView


urlpatterns = [
    path("register", UserRegistrationView.as_view(), name="register-user")
]

session_fileupload/feedback/profiles/urls.py
from django.urls import path
from .views import CreateProfileView, ListProfiles


urlpatterns = [
    path("", CreateProfileView.as_view()),
    path("list", ListProfiles.as_view()),
]

session_fileupload/feedback/reviews/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="review-index"),
    path("add", views.ReviewsView.as_view(), name="review-add"),
    path("thank-you", views.ThankYouView.as_view(), name="thank-you"),
    path("reviews", views.AllReviews.as_view(), name="all-reviews"),
    path("reviews/favorite", views.AddFavoriteReview.as_view(), name="favorite-review"),
    path("reviews/<int:pk>", views.SpecificReview.as_view(), name="selected-review"),
]

session_fileupload/feedback/feedbackusers/models.py
from django.db import models

# Create your models here.

session_fileupload/feedback/profiles/models.py
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    user_image = models.FileField(upload_to="images") # absolute path to the file
    # linux => /images
    # windows => C:/images

session_fileupload/feedback/reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Review(models.Model):
    user_name = models.CharField(max_length=50)
    review_text = models.TextField()
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])

session_fileupload/feedback/profiles/forms.py
from django import forms

class ProfileForm(forms.Form):
    user_image = forms.FileField()

session_fileupload/feedback/reviews/forms.py
from django import forms
from django.forms import fields, widgets
from .models import Review

# class ReviewForm(forms.Form):
#     user_name = forms.CharField(label="Your name", max_length=50, error_messages={
#         "required": "Please enter a name",
#         "max_length": "Please enter a shorter name"
#     })
#     review_text = forms.CharField(label="Your Feedback", widget=widgets.Textarea)
#     rating = forms.IntegerField(label="Your Rating", min_value=0, max_value=5)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        labels = {
            "user_name": "Your Name",
            "review_text": "Your Feedback",
            "rating": "Your Rating"
        }
        error_messages = {
            "user_name": {
                "required": "Please enter a name",
                "max_length": "Please enter a shorter name"
            }
        }

session_fileupload/feedback/feedbackusers/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

# Create your views here.
class UserRegistrationView(CreateView):
    template_name = "feedbackusers/registration.html"
    form_class = UserCreationForm
    success_url = reverse_lazy('review-index')

session_fileupload/feedback/profiles/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import CreateView, ListView

from .forms import ProfileForm
from .models import UserProfile


def store_file(file):
    with open("temp/image.jpg", "wb+") as dest:
        for chunk in file.chunks():
            dest.write(chunk)
    

class CreateProfileView(CreateView):
    model = UserProfile
    template_name = "profiles/upload_profile.html"
    success_url = "/profiles"
    fields = "__all__"


class ListProfiles(ListView):
    model = UserProfile
    template_name = "profiles/list_profiles.html"
    context_object_name = "profiles"


# Create your views here.
# class CreateProfileView(View):

#     def get(self, request):
#         form = ProfileForm()
#         return render(request, "profiles/upload_profile.html", {
#             "form": form
#         })

#     def post(self, request):
#         submitted_form = ProfileForm(request.POST, request.FILES)
#         if submitted_form.is_valid():
#             user_profile = UserProfile(user_image = request.FILES.get('user_image'))
#             user_profile.save()
#             return HttpResponseRedirect("/profiles")
#         return render(request, "profiles/upload_profile.html", {
#             "form": submitted_form
#         })

session_fileupload/feedback/reviews/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse



from .forms import ReviewForm
from .models import Review


# Create your views here.
class IndexView(TemplateView):
    template_name = "reviews/r_index.html"
    

class ReviewsView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    template_name = "reviews/reviews.html"
    success_url = "/thank-you"
    model = Review
    form_class = ReviewForm


class ThankYouView(TemplateView):
    template_name = "reviews/thank_you.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["message"] = "This is a message !!"
        return context_data


class AllReviews(ListView): # Getting Data
    template_name = "reviews/all_reviews.html"
    model = Review 
    context_object_name = "reviews"


class SpecificReview(DetailView):
    template_name = "reviews/specific_review.html"
    model = Review
    context_object_name = "review" 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fav_id = self.request.session.get("fav_review")
        review_obj = self.object
        is_fav = str(review_obj.id) == fav_id
        context["is_favorite"] = is_fav
        return context


class AddFavoriteReview(View):
    
    def post(self, request):
        review_id = request.POST["review_id"]
        request.session["fav_review"] = review_id 
        url = reverse("selected-review", args=review_id)
        return HttpResponseRedirect(url)

session_fileupload/feedback/feedbackusers/templates/feedbackusers/registration.html
{% extends 'reviews/base.html' %}

{% block title %}
Registration
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-control {% if field.errors %}errors{% endif %}">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <button>Register</button>
    </form>
{% endblock %}

session_fileupload/feedback/reviews/templates/reviews/all_reviews.html
{% extends 'reviews/base.html' %}
{% load static %}

{% block title %}
All Reviews
{% endblock title %}

{% block css_files %}
<link rel="stylesheet" href='{% static 'reviews/review_list.css' %}'/>
{% endblock css_files %}

{% block content %}
<ul>
    {% for review in reviews %}
        <li>
            <a href="{% url 'selected-review' review.id %}">{{ review.user_name }} | Rating : {{ review.rating }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock content %}

session_fileupload/feedback/reviews/templates/reviews/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'reviews/style.css' %}"/>
    {% block css_files %}
    {% endblock css_files %}
</head>
<body>
<header id="main-navigation">
    <h2>
       {% if user.is_authenticated %}
            <a href="{% url 'review-add' %}">Add</a><span>&nbsp;|&nbsp;</span>
       {% endif %}
        <a href="{% url 'all-reviews' %}">View</a><span>&nbsp;Review</span>
    </h2>
    
    <nav>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>&nbsp;&nbsp;<span>({{ user.get_username }})</span>
        {% else %}
            <a href="{% url 'login' %}">Login</a> <span>|</span>
            <a href="{% url 'register-user' %}">Register</a>
        {% endif %}
    </nav>
</header>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

session_fileupload/feedback/reviews/templates/reviews/r_index.html
{% extends 'reviews/base.html' %}

{% block title %}
Reviewer's
{% endblock %}
{% block content %}
  <div id="welcome_page">
    <h1>
      Welcome to Review Portal !!!!!!!
    </h1>
  </div>
{% endblock %}

session_fileupload/feedback/reviews/templates/reviews/reviews.html
{% extends 'reviews/base.html' %}

{% block title %}
Add Review
{% endblock %}
{% block content %}
    <form method="post" action="/">
        {% csrf_token %}
        {% for field in form%}
        <div class="form-control {% if field.errors %}errors{% endif %}">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <button>Send</button>
    </form>
{% endblock %}

session_fileupload/feedback/reviews/templates/reviews/specific_review.html
{% extends 'reviews/base.html' %}
{% load static %}

{% block title %}
Reviews Detail
{% endblock title %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'reviews/single_review.css' %}"/>
{% endblock css_files %}

{% block content %}
<div class="single_review">

    <div class="single_review_content">
        <p>
        {{ review.review_text|linebreaks }}
        </p>
    </div>

    <div class="footer_content">
        <p>{{ review.user_name }} ({{ review.rating }})</p>
    </div>
    {% if is_favorite %}
        <p>This is my favorite review !!</p>
    {% else %}
        <form method='POST' action="{% url 'favorite-review' %}">
            {% csrf_token %}
            <input type="hidden" name="review_id" value="{{ review.id }}"/>
            <button>Favorite</button>
        </form>
    {% endif %}
</div>
{% endblock %}

session_fileupload/feedback/reviews/templates/reviews/thank_you.html
{% extends 'reviews/base.html' %}
{% block title %}Thank you{% endblock %}
{% block content %}
<h1>Thank you !!</h1>
<p>
    {{ message }}
</p>
{% endblock %}